name: Deploy Website
on:
  push:
    branches:
      - master

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 20

    - run: mkdir -p dist
    - run: cp -rp ./favicon.ico ./dist
    - run: cp -rp ./favicon.png ./dist
    - run: cp -rp ./logo-dark.svg ./dist
    - run: cp -rp ./logo-light.svg ./dist
    - run: cp -rp ./uiw-1024x1024.png ./dist
    - run: cp -rp ./uiw.icns ./dist
    - run: cp -rp ./uiw.sketch ./dist

    - name: Website
      working-directory: dist
      run: |
        cat > index.html << EOF
        <!DOCTYPE html>
        <html lang="en">
        <head>
          <meta charset="UTF-8">
          <meta http-equiv="X-UA-Compatible" content="IE=edge">
          <meta name="viewport" content="width=device-width, initial-scale=1.0">
          <title>Source files of uiw's logo.</title>
          <style>
            .header { color: #333; text-align: center; padding: 80px 0 60px 0; min-height: 153px; font-size: 14px; }
            .content { text-align: center; }
            .content a span { display: inline-block; padding-top: 10px; padding-bottom: 10px; }
            .content a img { height: 60px; }
            .content a {
              display: inline-flex;
              justify-content: center;
              align-items: center;
              flex-direction: column;
              font-size: 12px;
              width: 120px;
              height: 120px;
              background-color: #e8e8e8;
              margin-top: 10px;
              padding: 16px;
            }
          </style>
        </head>
        <body>
          <a href="https://github.com/uiwjs/logo" target="_blank">Open Source</a>
          <div class="header">
            <img src="./logo-dark.svg" alt="uiw logo" width="120" />
          </div>
          <div class="content">
            <a href="./favicon.ico" target="_blank">
              <img src="./favicon.ico" alt="uiw favicon ico" />
              <span>favicon.ico</span>
            </a>
            <a href="./uiw.icns" target="_blank">
              <img src="./logo-dark.svg" alt="uiw icns" />
              <span>logo-dark.svg</span>
            </a>
            <a href="./uiw.sketch" target="_blank">
              <img src="./logo-dark.svg" alt="uiw sketch" />
              <span>uiw.sketch</span>
            </a>
          </div>
          <div class="content">
            <a href="./logo-dark.svg" target="_blank">
              <img src="./logo-dark.svg" alt="uiw logo dark" />
              <span>logo-dark.svg</span>
            </a>
            <a href="./logo-light.svg" target="_blank">
              <img src="./logo-light.svg" alt="uiw logo light" />
              <span>logo-light.svg</span>
            </a>
            <a href="./favicon.png" target="_blank">
              <img src="./favicon.png" alt="uiw favicon png" />
              <span>favicon.png</span>
            </a>
            <a href="./uiw-1024x1024.png" target="_blank">
              <img src="./uiw-1024x1024.png" alt="uiw-1024x1024.png" />
              <span>uiw-1024x1024.png</span>
            </a>
          </div>
        </body>
        </html>
        EOF

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./dist
